name: weatherly
description: A beautiful weather app with forecasts
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  geolocator: ^11.0.0
  permission_handler: ^11.0.0
  connectivity_plus: ^5.0.0
  video_player: ^2.8.2
  shared_preferences: ^2.2.2 
  chewie: ^1.7.0 
  provider: ^6.0.0
  intl: ^0.19.0
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  lottie: ^3.0.0
  equatable: ^2.0.5

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/videos/clear_sky.mp4
    - assets/lottie/